### ISSUE TITLE
Set Datadog API key and Application key manually

### ISSUE THREAD

**Issue by NomadBlacky** [NomadBlacky/digdag-plugin-datadog#1]
```yaml
+example:
  datadog_event>:
    api_key: "<my_api_key>"
    app_key: "<my_app_key>"
    title: "[TEST] digdag-plugin-datadog"
    text: "Digdag meets Datadog!!"
```
