### ISSUE TITLE
Set Datadog API key and Application key from secrets

### ISSUE THREAD

**Issue by NomadBlacky** [NomadBlacky/digdag-plugin-datadog#2]
```bash
$ digdag secrets --local --set datadog.api_key=<my_api_key>
$ digdag secrets --local --set datadog.app_key=<my_app_key>
```

```yaml
+example:
  datadog_event>:
    title: "[TEST] digdag-plugin-datadog"
    text: "Digdag meets Datadog!!"
```
