### ISSUE TITLE
Support `datadog_mertics>` operator

### ISSUE THREAD

**Issue by NomadBlacky** [NomadBlacky/digdag-plugin-datadog#3]
```yaml
+example2:
  datadog_metrics>:
    metric: digdag.example
    value: 10
    metric_type: gauge
    tags:
      - "key:value"
      - "project:digdag-plugin-datadog"
```
