### ISSUE TITLE
Support manually tags of the `datadog_event>` operator

### ISSUE THREAD

**Issue by NomadBlacky** [NomadBlacky/digdag-plugin-datadog#4]
```yaml
+example:
  datadog_event>:
    title: "[TEST] digdag-plugin-datadog"
    text: "Digdag meets Datadog!!"
    tags:
      - "key:value"
      - "project:digdag-plugin-datadog"
```
