### ISSUE TITLE
Markdown support for the `datadog_event` operator

### ISSUE THREAD

**Issue by NomadBlacky** [NomadBlacky/digdag-plugin-datadog#58]
The Datadog Event API doesn't use Markdown by default.  
[To use Markdown, need to add text block with `%%%` to the event text. ](https://docs.datadoghq.com/developers/events/email/?tab=json#markdown)

The `datadog_event` operator will support `markdown` parameter.  
If `true`, add text block with `%%%` to the event text.

```yaml
+example:
  datadog_event>:
    title: "[TEST] digdag-plugin-datadog"
    markdown: true
    text: |
      # We can use Markdown!

      + foo
          + bar

      ```
      source
      codes
      ```
```

![スクリーンショット 2020-02-26 20 30 29](https://user-images.githubusercontent.com/3215961/75341011-e4050000-58d6-11ea-84eb-445e625e7aff.png)
