### ISSUE TITLE
Support `alert_type` of the `datadog_events>` operator

### ISSUE THREAD

**Issue by NomadBlacky** [NomadBlacky/digdag-plugin-datadog#6]
```yaml
+example:
  datadog_event>:
    title: "[TEST] digdag-plugin-datadog"
    text: "Digdag meets Datadog!!"
    alert_type: info # or success, warning and error. default is info.
```
